# Generated by Django 3.2.17 on 2023-02-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ambulance_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
