# Generated by Django 3.2.17 on 2023-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0002_order_ambulance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='accident_pay_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
